name: "Setup Flutter"

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        cache-key: flutter-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}

    - name: Cache pub
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          pub-${{ runner.os }}-

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Get Dependencies
      shell: bash
      run: flutter pub get